### PR TITLE
Fix `mysql.dump()` (#1165)

### LINKED ISSUE #1165: mysql.dump password
## Describe the bug
`mysql.dump` errors out stating `mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: NO) when trying to connect` even though a password has been provided with `myqsl_password` parameter. Possibly an issue with the `mysqldump` package? I was able to use `mysql.database` and `mysql.load` operations with the same credentials without issue.

## To Reproduce
Use `mysql.dump` operation with a password. I am connecting to a local database with credentials root:root (super insecure because it's a development VM lol)

The following does not work, but I am able to use the same connection info with the `mysql.load` and `mysql.database` operations.
(database and destination are changed in my actual code)
```
mysql.dump(
    name="Dump database",
    database="<db_name>",
    mysql_host="localhost",
    mysql_user="root",
    mysql_password="root",
    dest="/home/<name>/<db_name>.sql",
)
```

## Expected behavior
I should be able to connect to the DB with the same credentials as the other operators?

## Meta
```
System: Linux
    Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
    Release: 5.15.153.1-microsoft-standard-WSL2
    Machine: x86_64
    pyinfra: v3.0.2
    Executable: /home/<name>/.local/bin/pyinfra
    Python: 3.10.12 (CPython, GCC 11.4.0)
```

- Installed PyInfra via Pip `pyinfra in /home/<name>/.local/lib/python3.10/site-packages (3.0.2)`
- `mysqldump` is also installed via Pip `mysqldump in /home/<name>/.local/lib/python3.10/site-packages (0.0.10)`

**The following is my actual code (with db and name scrubbed) and the debug output demonstrating that `mysql.database` works with the credentials provded, but `mysql.dump` does not:**
```
mysql.database(
    name="Create <db_name> database",
    database="<db_name>",
    mysql_host="localhost",
    mysql_user="root",
    mysql_password="root",
)

mysql.dump(
    name="Dump database",
    database="<db_name>",
    mysql_host="localhost",
    mysql_user="root",
    mysql_password="root",
    dest="/home/<name>/<db_name>.sql",
)
```

```
--> Starting operation: Create <db_name> database
    [pyinfra.api.operations] Starting operation {'Create <database_name> database'} on @local
    [pyinfra.api.facts] Getting fact: mysql.MysqlDatabases (mysql_host=localhost, mysql_password=root, mysql_port=None, mysql_user=root) (ensure_hosts: None)

[pyinfra.connectors.local] --> Running command on localhost: sh -c '! command -v mysql >/dev/null || mysql -u"root" *** -hlocalhost -Be '"'"'SELECT * FROM information_schema.SCHEMATA'"'"''
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
    [pyinfra.api.facts] [@local] Loaded fact mysql.MysqlDatabases (mysql_host=localhost, mysql_password=root, mysql_port=None, mysql_user=root)
    [pyinfra.api.host] [@local] noop: mysql database <db_name> exists
    [@local] No changes

--> Starting operation: Dump database
    [pyinfra.api.operations] Starting operation {'Dump database'} on @local

[pyinfra.connectors.local] --> Running command on localhost: sh -c 'mysqldump <db_name> -u"root" *** -hlocalhost > /home/<name>/<db_name>.sql'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 2
    [@local] mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: NO) when trying to connect
    [@local] Error: executed 0 commands
    [pyinfra.api.state] Failing hosts: @local

--> Disconnecting from hosts...
--> pyinfra error: No hosts remaining!
```

### PR DESCRIPTION
**Pull request by simonhammes**
Fixes #1165

I tested this manually. The code now uses the same structure as `mysql.load()`.

### CODE REVIEW

**Comment by simonhammes** [comment]
Any idea why the tests fail? The test case returns **two** commands, but should only return a single command:

https://github.com/pyinfra-dev/pyinfra/actions/runs/10324005007/job/28582572363?pr=1169#step:5:189

Is this because of the nested command?

(`make_mysql_command()` returns a command, which is wrapped inside another `StringCommand`)

**Comment by Fizzadar** [comment]
@simonhammes the test is failing because I made some poor choices on testing masked vs. non-masked commands! Secretly the tests will expand these into a list of `[value, masked]`. I'm pushing up a fix for this to a more explicit dict object.

**Review by Fizzadar — APPROVED** [review]
Thank you for fixing this @simonhammes! Pushed up a fix for my test mess 😬

**Comment by simonhammes** [comment]
> Thank you for fixing this @simonhammes! Pushed up a fix for my test mess 😬

No worries, thank you very much for the quick fix!

**Pull request merged**
