### PR TITLE
Bump paramiko major version

### PR DESCRIPTION
**Pull request by pbsds**
Tested with paramiko 3.3.1

```
pyinfra> ============================= test session starts ==============================
pyinfra> platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
pyinfra> rootdir: /build/source
pyinfra> configfile: setup.cfg
pyinfra> collected 1074 items / 27 deselected / 1047 selected                           
pyinfra> 
pyinfra> tests/test_facts.py .................................................... [  4%]
pyinfra> ........................................................................ [ 11%]
pyinfra> ........................................................................ [ 18%]
pyinfra> ......                                                                   [ 19%]
pyinfra> tests/test_global_arguments.py .                                         [ 19%]
pyinfra> tests/test_operations.py ............................................... [ 23%]
pyinfra> ........................................................................ [ 30%]
pyinfra> ........................................................................ [ 37%]
pyinfra> ........................................................................ [ 44%]
pyinfra> ........................................................................ [ 51%]
pyinfra> ........................................................................ [ 58%]
pyinfra> ........................................................................ [ 65%]
pyinfra> ........................................................................ [ 72%]
pyinfra> .......................................................                  [ 77%]
pyinfra> tests/test_operations_utils.py ....                                      [ 77%]
pyinfra> tests/test_api/test_api.py ....                                          [ 78%]
pyinfra> tests/test_api/test_api_arguments.py ....                                [ 78%]
pyinfra> tests/test_api/test_api_command.py ...............                       [ 79%]
pyinfra> tests/test_api/test_api_config.py ..                                     [ 80%]
pyinfra> tests/test_api/test_api_deploys.py ..                                    [ 80%]
pyinfra> tests/test_api/test_api_facts.py ............                            [ 81%]
pyinfra> tests/test_api/test_api_host.py ....                                     [ 81%]
pyinfra> tests/test_api/test_api_inventory.py ....                                [ 82%]
pyinfra> tests/test_api/test_api_operations.py ..................                 [ 83%]
pyinfra> tests/test_api/test_api_util.py ....                                     [ 84%]
pyinfra> tests/test_cli/test_cli.py ..................                            [ 85%]
pyinfra> tests/test_cli/test_cli_deploy.py ...                                    [ 86%]
pyinfra> tests/test_cli/test_cli_exceptions.py ....                               [ 86%]
pyinfra> tests/test_cli/test_cli_util.py .........                                [ 87%]
pyinfra> tests/test_cli/test_context_objects.py ........                          [ 88%]
pyinfra> tests/test_connectors/test_ansible.py ....                               [ 88%]
pyinfra> tests/test_connectors/test_chroot.py ..........                          [ 89%]
pyinfra> tests/test_connectors/test_docker.py ............                        [ 90%]
pyinfra> tests/test_connectors/test_dockerssh.py .............                    [ 91%]
pyinfra> tests/test_connectors/test_local.py .............                        [ 93%]
pyinfra> tests/test_connectors/test_mech.py ...                                   [ 93%]
pyinfra> tests/test_connectors/test_ssh.py ...............................        [ 96%]
pyinfra> tests/test_connectors/test_sshuserclient.py ...                          [ 96%]
pyinfra> tests/test_connectors/test_terraform.py ........                         [ 97%]
pyinfra> tests/test_connectors/test_util.py ....................                  [ 99%]
pyinfra> tests/test_connectors/test_vagrant.py ...                                [ 99%]
pyinfra> tests/test_connectors/test_winrm.py ...                                  [100%]
```

### CODE REVIEW

**Comment by totoroot** [comment]
@Fizzadar Could this small change get merged? Does anything speak against it?
`pyinfra` currently has to get patched on NixOS due to this requirement.

**Comment by Fizzadar** [comment]
> @Fizzadar Could this small change get merged? Does anything speak against it?
> `pyinfra` currently has to get patched on NixOS due to this requirement.

Honestly I totally missed this PR, will try land this asap!

**Comment by Fizzadar** [comment]
Failing CI is unrelated to this. Thank you @pbsds for the PR and apologies all for taking so long to merge this one!

**Comment by themanifold** [comment]
@Fizzadar when will this be released as a new package on pypi? Consider doing an emergency release as paramiko >3.4 contains the mitigation for terrapin: https://github.com/advisories/GHSA-45x7-px36-x8w8

**Pull request merged**
