### PR TITLE
Add flatpak packages support

### PR DESCRIPTION
**Pull request by JustScreaMy**
This pull request should add a basic flatpak packages support. It would be nice to be able to add additional remotes, but I guess that i can finish that another time.

### CODE REVIEW

**Review by Fizzadar — CHANGES_REQUESTED** [review]
Thank you for the PR @JustScreaMy! Code looks good here just linting issues and this is good to go :)

**Comment by JustScreaMy** [comment]
Okay, I have no idea what it wants from me. Running flake8 locally doesn't even see that as an issue, just screams about "Possibly misspelt words". Do you have any idea what it is complaining about?
```
./pyinfra/facts/flatpak.py:8:7: SC200 Possibly misspelt word: 'Flatpak'
./pyinfra/facts/flatpak.py:15:7: SC200 Possibly misspelt word: 'Flatpak'
./pyinfra/facts/flatpak.py:15:22: SC200 Possibly misspelt word: 'Flatpak'
./pyinfra/facts/flatpak.py:49:7: SC200 Possibly misspelt word: 'Flatpak'
./pyinfra/facts/flatpak.py:49:23: SC200 Possibly misspelt word: 'Flatpak'
./pyinfra/facts/flatpak.py:70:17: SC200 Possibly misspelt word: 'flatpak'
./pyinfra/facts/flatpak.py:70:29: SC200 Possibly misspelt word: 'flatpak'
./pyinfra/facts/zfs.py:8:14: SC200 Possibly misspelt word: 'zfs'
./pyinfra/facts/zfs.py:9:5: SC200 Possibly misspelt word: 'datasets'
./pyinfra/facts/zfs.py:11:9: SC200 Possibly misspelt word: 'dataset'
./pyinfra/facts/zfs.py:12:12: SC200 Possibly misspelt word: 'dataset'
./pyinfra/facts/zfs.py:12:27: SC200 Possibly misspelt word: 'datasets'
./pyinfra/facts/zfs.py:13:13: SC200 Possibly misspelt word: 'datasets'
./pyinfra/facts/zfs.py:13:22: SC200 Possibly misspelt word: 'dataset'
./pyinfra/facts/zfs.py:14:9: SC200 Possibly misspelt word: 'datasets'
./pyinfra/facts/zfs.py:14:18: SC200 Possibly misspelt word: 'dataset'
./pyinfra/facts/zfs.py:15:12: SC200 Possibly misspelt word: 'datasets'
./pyinfra/facts/zfs.py:24:25: SC200 Possibly misspelt word: 'zfs'
./pyinfra/facts/zfs.py:27:7: SC200 Possibly misspelt word: 'Datasets'
./pyinfra/facts/zfs.py:33:25: SC200 Possibly misspelt word: 'zfs'
./pyinfra/facts/zfs.py:36:7: SC200 Possibly misspelt word: 'Filesystems'
./pyinfra/facts/zfs.py:37:12: SC200 Possibly misspelt word: 'Datasets'
./pyinfra/facts/zfs.py:45:12: SC200 Possibly misspelt word: 'Datasets'
./pyinfra/facts/zfs.py:53:12: SC200 Possibly misspelt word: 'Datasets'
./pyinfra/operations/flatpak.py:9:20: SC200 Possibly misspelt word: 'flatpak'
./pyinfra/operations/flatpak.py:9:35: SC200 Possibly misspelt word: 'Flatpak'
./pyinfra/operations/flatpak.py:14:5: BLK100 Black would make changes.
./pyinfra/operations/flatpak.py:53:5: SC200 Possibly misspelt word: 'flatpak'
./pyinfra/operations/flatpak.py:53:38: SC200 Possibly misspelt word: 'Flatpak'
./pyinfra/operations/flatpak.py:60:23: SC200 Possibly misspelt word: 'flatpak'
./pyinfra/operations/flatpak.py:66:27: SC200 Possibly misspelt word: 'flatpak'
./pyinfra/operations/zfs.py:7:20: SC200 Possibly misspelt word: 'zfs'
./pyinfra/operations/zfs.py:7:31: SC200 Possibly misspelt word: 'Datasets'
./pyinfra/operations/zfs.py:11:5: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:12:5: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:47:44: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:51:5: SC200 Possibly misspelt word: 'datasets'
./pyinfra/operations/zfs.py:51:30: SC200 Possibly misspelt word: 'Datasets'
./pyinfra/operations/zfs.py:53:14: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:53:24: SC200 Possibly misspelt word: 'datasets'
./pyinfra/operations/zfs.py:53:37: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:55:33: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:66:59: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:68:31: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:71:62: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:75:65: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:79:19: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:81:59: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:109:20: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:141:16: SC200 Possibly misspelt word: 'dataset'
./pyinfra/operations/zfs.py:170:16: SC200 Possibly misspelt word: 'dataset'
./tests/test_api/test_api_inventory.py:64:9: SC200 Possibly misspelt word: 'hosthost'
./tests/test_api/test_api_inventory.py:68:9: SC200 Possibly misspelt word: 'hosthost'
./tests/test_api/test_api_inventory.py:69:16: SC200 Possibly misspelt word: 'hosthost'
./tests/test_api/test_api_inventory.py:73:9: SC200 Possibly misspelt word: 'hosthost'
./tests/test_api/test_api_inventory.py:73:23: SC200 Possibly misspelt word: 'somethingelse'
./tests/test_api/test_api_inventory.py:74:16: SC200 Possibly misspelt word: 'hosthost'
./tests/test_api/test_api_inventory.py:74:30: SC200 Possibly misspelt word: 'somethingelse'
```

**Comment by simonhammes** [comment]
@JustScreaMy Thank you for working on this! 

I've tried out your PR. However I'm not able to install packages which require permissions.

I believe the `--noninteractive` flag would fix that. Or did you leave that out on purpose?

FWIW, the Ansible module also passes this flag (or `--assumeyes` for really old versions):
https://github.com/ansible-collections/community.general/blob/132faeae3455e3e57cca8af70c314a2b244f4087/plugins/modules/flatpak.py#L205

**Comment by JustScreaMy** [comment]
> I believe the `--noninteractive` flag would fix that. Or did you leave that out on purpose?

Hi! Thank you for trying it. This is a mistake on my side, I have forgot to commit these few lines. Will fix it

**Comment by simonhammes** [comment]
> Okay, I have no idea what it wants from me. Running flake8 locally doesn't even see that as an issue, just screams about "Possibly misspelt words". Do you have any idea what it is complaining about?

I think you need to run `black` locally (e.g. `pipx run black pyinfra`) since CI complains about formatting. This produces the following diff:

```diff
diff --git a/pyinfra/operations/flatpak.py b/pyinfra/operations/flatpak.py
index e6045b13..ae2bf635 100644
--- a/pyinfra/operations/flatpak.py
+++ b/pyinfra/operations/flatpak.py
@@ -11,8 +11,8 @@ from pyinfra.facts.flatpak import FlatpakPackages
 
 @operation()
 def package(
-        packages: str | list[str] | None = None,
-        present=True,
+    packages: str | list[str] | None = None,
+    present=True,
 ):
     """
     Install/remove a flatpak package
```

**Comment by JustScreaMy** [comment]
Thanks for the tip! I though that `scripts/dev-lint.sh` already runs black but as it seems, there is only flake8 and mypy type checking

**Review by Fizzadar — APPROVED** [review]
Thank you for the PR & fixes @JustScreaMy!

I've just pushed up https://github.com/pyinfra-dev/pyinfra/commit/a509f954aa4d735ddc388156c73cbe6a73c5994d which should make this less painful for future maintainers by actually running `black` in the linting script!

I have also pushed https://github.com/pyinfra-dev/pyinfra/commit/4adb3a802c70aef4d01095af7c3eb80a088086d8 to suppress the spellcheck linting.

**Comment by Fizzadar** [comment]
Note @JustScreaMy - I just renamed `flatpak.package` -> `flatpak.packages` for consistency with other operations!

**Pull request merged**
