### PR TITLE
Improve crontab

### LINKED ISSUE #1189: server.crontab() not identifying cronjobs
## Describe the bug
If this is not a bug I am horribly confused on how this is actually supposed to work. 🙃

If an unidentified cronjob exists in your crontab and you attempt to identify this cronjob with the `cron_name` argument, this does not add an identifier to the cronjob. You must then make another call to `server.crontab()` with the same `cron_name` if you want to make changes to the cronjob. This time however, instead of overwriting the existing cronjob that you just tried to identify, `server.crontab()` will create a new entry in your crontab - appending it to the end of the file - leaving you with the cronjob you initially tried to identify as well as the new cronjob with the identifier you tried to apply to the initial cronjob. 

## To Reproduce
Have a crontab with some cronjobs in it that aren't identified by PyInfra, then run `server.crontab()` against your crontab in an attempt to identify the cronjobs, and then modify them afterwards.

+ Operation code & usage
```
server.crontab(
    name="Identify Cron",
    command=f"/usr/bin/php{php_version} {old_estore_dir}/bin/magento cron:run 2>&1 \
| grep -v \"Ran jobs by schedule\" >> {old_estore_dir}/var/log/magento.cron.log",
    minute="*",
    hour="*",
    month="*",
    day_of_week="*",
    day_of_month="*",
    present=True,
    user=f"{username}",
    cron_name=f"{site}_cron",
    _sudo=True,
)

server.crontab(
    name="Modify Cron",
    command=f"/usr/bin/php{php_version} {estore_dir}/bin/magento cron:run 2>&1 \
| grep -v \"Ran jobs by schedule\" >> {estore_dir}/var/log/magento.cron.log",
    minute="*",
    hour="*",
    month="*",
    day_of_week="*",
    day_of_month="*",
    present=True,
    user=f"{username}",
    cron_name=f"{site}_cron",
    _sudo=True,
)
```

If I attempt to identify and modify either of the cronjobs, I get a brand new cronjob appended to the end of the file as shown, with the cron identifier. In this example I tried to edit the staging_cron

**Before**
```
* * * * * /usr/bin/php8.2 /opt/<name>/apps/prod/estore.e483eac1/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/prod/estore.e483eac1/var/log/magento.cron.log

* * * * * /usr/bin/php8.2 /opt/<name>/apps/staging/estore.1312e8dd/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/staging/estore.1312e8dd/var/log/magento.cron.log
```

**After**
```
* * * * * /usr/bin/php8.2 /opt/<name>/apps/prod/estore.e483eac1/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/prod/estore.e483eac1/var/log/magento.cron.log

* * * * * /usr/bin/php8.2 /opt/<name>/apps/staging/estore.1312e8dd/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/staging/estore.1312e8dd/var/log/magento.cron.log

# pyinfra-name=staging_cron
* * * * * /usr/bin/php8.2 /opt/<name>/apps/staging/estore.656bc6af/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/staging/estore.656bc6af/var/log/magento.cron.log
```

## Expected behavior
The cronjob should be identified with the first call to `server.crontab()`, prepending the `cron_name` identifier/comment on the line above the cronjob. Then, the second call to `server.crontab()` should overwrite this cronjob with the new contents if the same `cron_name` is used, not appending a new cronjob to the end of the file, and not leaving the initial cronjob behind.

## Meta
```
System: Linux
      Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
      Release: 5.15.153.1-microsoft-standard-WSL2
      Machine: x86_64
    pyinfra: v3.1
      click: v8.1.7
      configparser: v7.1.0
      distro: v1.9.0
      gevent: v24.2.1
      jinja2: v3.1.4
      packaging: v24.1
      paramiko: v3.4.1
      python-dateutil: v2.9.0.post0
      pywinrm: v0.5.0
      setuptools: v73.0.1
      typeguard: v4.3.0
      typing-extensions: v4.12.2
      wheel: v0.44.0
    Executable: /home/<name>/<project>/env/bin/pyinfra
    Python: 3.10.12 (CPython, GCC 11.4.0)
  ```
+ How was pyinfra installed? **Pip**

+ Debug info:
```
--> Starting operation: Identify Cron
    [pyinfra.api.operations] Starting operation {'Identify Cron'} on @local
    [pyinfra.api.facts] Getting fact: server.Crontab (user=<name>) (ensure_hosts: None)

[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c '! command -v crontab >/dev/null || crontab -l -u <name> || true'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
    [pyinfra.api.facts] [@local] Loaded fact server.Crontab (user=<name>)
    [pyinfra.api.host] [@local] noop: crontab /usr/bin/php8.2 /opt/<name>/apps/staging/estore.1312e8dd/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/staging/estore.1312e8dd/var/log/magento.cron.log exists
    [@local] No changes

--> Starting operation: Modify Cron
    [pyinfra.api.operations] Starting operation {'Modify Cron'} on @local
    [pyinfra.api.facts] Getting fact: server.Crontab (user=<name>) (ensure_hosts: None)

[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c '! command -v crontab >/dev/null || crontab -l -u <name> || true'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
    [pyinfra.api.facts] [@local] Loaded fact server.Crontab (user=<name>)

[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'crontab -l -u <name>> /tmp/pyinfra-99800753387583ff6590a828b5571df23d46c9b6'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'echo '"'"''"'"' >> /tmp/pyinfra-99800753387583ff6590a828b5571df23d46c9b6'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'echo '"'"'# pyinfra-name=staging_cron'"'"' >> /tmp/pyinfra-99800753387583ff6590a828b5571df23d46c9b6'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'echo '"'"'* * * * * /usr/bin/php8.2 /opt/<name>/apps/staging/estore.656bc6af/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/staging/estore.656bc6af/var/log/magento.cron.log'"'"' >> /tmp/pyinfra-99800753387583ff6590a828b5571df23d46c9b6'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'crontab -u <name> /tmp/pyinfra-99800753387583ff6590a828b5571df23d46c9b6'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
    [@local] Success
```

### LINKED ISSUE #1191: host.get_fact(Crontab) is not able to handle crontab-level environment variables like CRON_TZ
## Describe the bug
I need to enforce CRON_TZ=UTC in my crontab. changing machine's timezone is not possible
But pyinfra can't parse the line: 
```log
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.12/site-packages/pyinfra_cli/util.py", line 65, in exec_file
    exec(PYTHON_CODES[filename], data)
  File "***.py", line 15, in <module>
    server.crontab(
  File "/opt/homebrew/lib/python3.12/site-packages/pyinfra/api/operation.py", line 295, in decorated_func
    for _ in command_generator():
  File "/opt/homebrew/lib/python3.12/site-packages/pyinfra/api/operation.py", line 282, in command_generator
    for command in func(*args, **kwargs):
  File "/opt/homebrew/lib/python3.12/site-packages/pyinfra/operations/server.py", line 655, in crontab
    crontab = host.get_fact(Crontab, user=user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pyinfra/api/host.py", line 350, in get_fact
    return get_host_fact(self.state, self, name_or_cls, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pyinfra/api/facts.py", line 320, in get_host_fact
    return get_fact(state, host, cls, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pyinfra/api/facts.py", line 188, in get_fact
    return _get_fact(
           ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pyinfra/api/facts.py", line 272, in _get_fact
    data = fact.process(stdout_lines)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pyinfra/facts/server.py", line 437, in process
    minute, hour, day_of_month, month, day_of_week, command = line.split(None, 5)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 6, got 1)
```

## To Reproduce
Steps to reproduce the behavior, please include where possible:

+ Operation code & usage
```crontab
CRON_TZ=UTC
```
```python
host.get_fact(Crontab)
```
+ Target system information
ubuntu

## Expected behavior
pyinfra handles this CRON_TZ, or at least ignore it

## Meta
+ Include output of `pyinfra --support`.
```

    System: Darwin
      Platform: macOS-14.5-arm64-arm-64bit
      Release: 23.5.0
      Machine: arm64
    pyinfra: v3.0.2
    Executable: /opt/homebrew/bin/pyinfra
    Python: 3.12.5 (CPython, Clang 15.0.0 (clang-1500.3.9.4))
```
+ How was pyinfra installed (source/pip)?
source
+ Include pyinfra-debug.log (if one was created)
+ Consider including output with `-vv` and `--debug`.
```log
[work-data] >>> sh -c '! command -v crontab >/dev/null || crontab -l || true'
[work-data] # Edit this file to introduce tasks to be run by cron.
[work-data] # 
[work-data] # Each task to run has to be defined through a single line
[work-data] # indicating with different fields when the task will be run
[work-data] # and what command to run for the task
[work-data] # 
[work-data] # To define the time you can provide concrete values for
[work-data] # minute (m), hour (h), day of month (dom), month (mon),
[work-data] # and day of week (dow) or use '*' in these fields (for 'any').
[work-data] # 
[work-data] # Notice that tasks will be started based on the cron's system
[work-data] # daemon's notion of time and timezones.
[work-data] # 
[work-data] # Output of the crontab jobs (including errors) is sent through
[work-data] # email to the user the crontab file belongs to (unless redirected).
[work-data] # 
[work-data] # For example, you can run a backup of all your user accounts
[work-data] # at 5 a.m every week with:
[work-data] # 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
[work-data] # 
[work-data] # For more information see the manual pages of crontab(5) and cron(8)
[work-data] # 
[work-data] # m h  dom mon dow   command
[work-data] CRON_TZ=UTC
```

### LINKED ISSUE #1192: Crontab fact can't handle same command in multiple entries
I noticed that Crontab uses the following data structure. If a command appears twice, the old entry will get overwritten. It may has something to do with #1189, but I'm not sure
```python
class Crontab(FactBase[Dict[str, CrontabDict]]):
    """
    Returns a dictionary of cron command -> execution time.

    .. code:: python

        {
            "/path/to/command": {
                "minute": "*",
                "hour": "*",
                "month": "*",
                "day_of_month": "*",
                "day_of_week": "*",
            },
            "echo another command": {
                "special_time": "@daily",
            },
        }
    """
```

Proposal:
use the new data structure
```python
  {
    "entries": [
        {
          "env": "CRON_TZ",
          "value": "UTC"
        },
        {
          "command": "/path/to/command",
          "minute": "*"
        },
        {
          "command": "echo another command",
          "special_time": "@daily",
        },
    ],
    "/path/to/command": {
        "minute": "*",
        "hour": "*",
        "month": "*",
        "day_of_month": "*",
        "day_of_week": "*",
    },
    "echo another command": {
        "special_time": "@daily",
    },
}
```
and deprecate old structure

### PR DESCRIPTION
**Pull request by JakkuSakura**
This should be able to fix #1192, fix #1191, fix #1189

### CODE REVIEW

**Comment by JakkuSakura** [comment]
I'm getting weird output from sed though
```log
>>> sh -c 'sed -i.2409030207 '"'"'s/.*{'"'"'"'"'"'"'"'"'command'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'***.py --date UTC_YESTERDAY --directory trading\/data >>***\/log\/***.log'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'minute'"'"'"'"'"'"'"'"': 0, '"'"'"'"'"'"'"'"'hour'"'"'"'"'"'"'"'"': 1, '"'"'"'"'"'"'"'"'month'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'*'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'day_of_month'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'*'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'day_of_week'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'*'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'comments'"'"'"'"'"'"'"'"': ['"'"'"'"'"'"'"'"'# pyinfra-name=trading-market-convert'"'"'"'"'"'"'"'"']}.*/0 1 * * * {'"'"'"'"'"'"'"'"'command'"'"'"'"'"'"'"'"': "{'"'"'"'"'"'"'"'"'command'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'***.py --date UTC_YESTERDAY --directory trading\/data >> ***.log'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'minute'"'"'"'"'"'"'"'"': 0, '"'"'"'"'"'"'"'"'hour'"'"'"'"'"'"'"'"': 1, '"'"'"'"'"'"'"'"'month'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'*'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'day_of_month'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'*'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'day_of_week'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'*'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'comments'"'"'"'"'"'"'"'"': ['"'"'"'"'"'"'"'"'# pyinfra-name=***'"'"'"'"'"'"'"'"']}", '"'"'"'"'"'"'"'"'minute'"'"'"'"'"'"'"'"': 0, '"'"'"'"'"'"'"'"'hour'"'"'"'"'"'"'"'"': 1, '"'"'"'"'"'"'"'"'month'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'*'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'day_of_month'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'*'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'day_of_week'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'*'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'comments'"'"'"'"'"'"'"'"': ['"'"'"'"'"'"'"'"'# pyinfra-name=***'"'"'"'"'"'"'"'"']}/'"'"' /tmp/pyinfra-9131c353368aca911dc6ed509e9c034d952750ed && rm -f /tmp/pyinfra-9131c353368aca911dc6ed509e9c034d952750ed.2409030207'
```

**Comment by simonhammes** [comment]
@JakkuSakura Can you fix the linting issues? Running `./scripts/dev-lint.sh` should be enough. 

Make sure that you've activated the virtual environment in advance to ensure that the script uses the correct tool versions (and not some globally installed versions).

**Comment by JakkuSakura** [comment]
Hi, I fixed the linting and squashed the commits.

**Review by Fizzadar — APPROVED** [review]
Well this is awesome, thank you @JakkuSakura!

I suppose it's sort-of backwards compatible - by which I mean the use of the fact can be identical to before, but technically the types have changed in a non-compatible way. But resulting UX works and this is a significant improvement, I think that wins.

**Pull request merged**
