### PR TITLE
error out under the right conditions

### PR DESCRIPTION
**Pull request by FooBarQuaxx**
I run into a weird issue where clearly pyinfra should not error out. This PR is probably the right fix.

### CODE REVIEW

**Comment by FooBarQuaxx** [comment]
Yes, I will share in it later today.

**Comment by FooBarQuaxx** [comment]
This is something close to what lead me to find the error fixed by the PR:
```bash
$ cat kernel_modules.py
from pyinfra.api import deploy
from pyinfra.operations import server


@deploy('Load kernel Modules')
def load_kernel_modules(state, host):

    modules = ['raid1']
    server.modprobe(
        name='Add modules',
        module=modules
    )


load_kernel_modules()

$ cat deploy.py
from pyinfra import local

SUDO = True
local.include('kernel_modules.py')

$ pyinfra --debug @local deploy.py 
    [pyinfra_cli.main] Checking potential directory: 
    [pyinfra_cli.main] Checking potential directory: 
--> Loading config...
--> Loading inventory...
    [pyinfra_cli.inventory] Creating fake inventory...

--> Connecting to hosts...
    [@local] Connected
    [pyinfra.api.state] Activating host: @local

--> Preparing operations...
    Loading: deploy.py
    [pyinfra.local] Including local file: kernel_modules.py
    [pyinfra.api.state] Starting deploy kernel_modules.py (args={}, data=None)
    [pyinfra.api.deploy] Adding deploy, called @ kernel_modules.py:15
    [pyinfra.api.state] Starting deploy kernel_modules.py | Load kernel Modules (args={'sudo': True, 'sudo_user': None, 'use_sudo_login': False, 'use_sudo_password': False, 'preserve_sudo_env': False, 'su_user': None, 'use_su_login': False, 'name': None, 'shell_executable': None, 'env': {}, 'ignore_errors': False, 'success_exit_codes': [0], 'timeout': None, 'get_pty': None, 'stdin': None, 'parallel': None, 'run_once': None, 'serial': None, 'on_success': None, 'on_error': None}, data=None)
--> [@local] pyinfra error: Nested deploy operation called without state/host: server.modprobe (line 11 in kernel_modules.py)
```

**Comment by Fizzadar** [comment]
@FooBarQuaxx I've just been working on the deploy API and discovered this actually _is_ intentional! Although it won't cause any harm in CLI mode the check exists to ensure that `@deploy` functions can also work in API mode. Specifically the example should pass state/host:

```py
@deploy('Load kernel Modules')
def load_kernel_modules(state, host):

    modules = ['raid1']
    server.modprobe(
        name='Add modules',
        module=modules
        state=state,
        host=host,
    )
```

Totally on me for not spotting this originally, will correct in `v1.2`!

**Comment by Fizzadar** [comment]
(I've also expanded the docs to explain this properly @ https://docs.pyinfra.com/en/1.x/api/deploys.html).

**Pull request merged**
