### PR TITLE
Added support for YAML/JSON-formatted Ansible inventories in @ansible.

### PR DESCRIPTION
**Pull request by ricardbejarano**
Caused by #301.

I've refactored the `@ansible` connector into supporting "format parser routing", to enroute the inventory file into a supporting parser (INI, JSON or YAML; for now) based on its format, as well as leaving the door open for new formats to come.

I left the INI parsing logic untouched.
**Warning: I've found the INI parser does not support hosts outside any section, you may want to take a look into that. I can create a separate issue if you will.**

I've tested all three formats with the Ansible inventories shown [here](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html) (I manually translated the YAML into JSON since there's no JSON-formatted inventories in that page), as well as one of my own large YAML inventories. **It works just as expected.**

***Note 1:** I assume (haven't checked) that the logic calling `make_names_data` does not manipulate inventory file names.*

***Note 2:** Not sure what `@memoize` does. Google says it's to optimize, but I don't know what constraints it introduces, so I didn't memoize `make_names_data`. Let me know if it's optimum to wrap it based on the routine's tasks.*

### CODE REVIEW

**Comment by ricardbejarano** [comment]
***Note 3:** we may want to add tests for JSON/YAML-formatted inventories. I'm not familiar with this project's testing so I'd highly appreciate it if someone else did. I can provide the inventory files.*

**Comment by ricardbejarano** [comment]
@Fizzadar those CI tests have been stuck for 10 hours now, am I supposed to trigger them or something? Never seen tests take these long, so I'm guessing they're not even running?

**Comment by Fizzadar** [comment]
@ricardbejarano thank you for the PR!, re notes:

1. This is correct it will be passed everything after the slash in `@ansible/XXX`
2. We can drop the `@memoize` call - memoize is only really useful here to show the warning (so it only shows once). I think the memoize on loading the inventory file is invalid, I will remove it
3. The current test is very simple (https://github.com/Fizzadar/pyinfra/blob/master/tests/test_connectors/test_ansible.py), it should be just a case of adding the test inventories into the test deploy directory and calling there

And re:CI - I'm investigating this, looks like the Travis integration is broken somehow. The tests _have_ run (failed) - https://travis-ci.org/github/Fizzadar/pyinfra/pull_requests. Need to add `pyyaml` as a requirement, which I think should be an extra requirement rather than major.

If you add me as a collaborator I'm happy to setup the yaml requirement and additional test inventories.

**Comment by Fizzadar** [comment]
@ricardbejarano thank you for sending those over; I've now added the extra and tests in https://github.com/Fizzadar/pyinfra/pull/303/commits/8027039959c1667cb524f0c46ce6fc75cf8a4fdf + https://github.com/Fizzadar/pyinfra/pull/303/commits/4034e2a1aa765167f760c428cf142452b1326e72, will merge this once tests pass :)

**Comment by ricardbejarano** [comment]
@Fizzadar at this point I don't know what's making flake8 err out.
I'll let you fix that since I'm not familiar with it.

**Comment by Fizzadar** [comment]
All fixed, thank you for the PR @ricardbejarano!

**Pull request merged**
