### PR TITLE
pyinfra/connectors: Fix overwriting of users known_hosts file (#1209)

### PR DESCRIPTION
**Pull request by evoldstad**
This fixes issue #1209, making it so that we append new keys to the users known_hosts file instead of overwriting it.

Additionally:
- Added a testcase that should discover this breaking in the future
- Broke out the append functionality into a "append_hostkey" function, making it so we don't needlessly reuse code for AskPolicy 
- Linting actually correct this time.
- Merged commits correctly this time. 

Previous behaviour when adding a new 
- Create a paramiko.HostKeys object 
- Read the users known_hosts file  
- Add the new key to the paramiko object.  
- Save the object, overwriting the users host_keys file without comments and entries incompatible with paramiko. 

New behaviour:
- Create a paramiko.HostKeyEntry object using the new hostname and
corresponding key.
- Append this key to the existing known_hosts file.

### CODE REVIEW

**Comment by evoldstad** [comment]
The spelling issue seems to be a false positive, as it reacts on a part of the example key used in the test. Any way to override this behaviour, or mark it as a non-issue?

**Comment by simonhammes** [comment]
> The spelling issue seems to be a false positive, as it reacts on a part of the example key used in the test. Any way to override this behaviour, or mark it as a non-issue?

You can either ignore the whole file or ignore certain expressions based on regular expressions: https://github.com/pyinfra-dev/pyinfra/blob/3.x/.typos.toml

**Comment by evoldstad** [comment]
> > The spelling issue seems to be a false positive, as it reacts on a part of the example key used in the test. Any way to override this behaviour, or mark it as a non-issue?
> 
> You can either ignore the whole file or ignore certain expressions based on regular expressions: https://github.com/pyinfra-dev/pyinfra/blob/3.x/.typos.toml

Thanks, that fixed it!

**Review by Fizzadar — APPROVED** [review]
Amazing, thank you for fixing this @evoldstad!

**Pull request merged**
