### PR TITLE
Add psql_database argument postgres operations/facts

### PR DESCRIPTION
**Pull request by hamishfagg**
This PR adds the ability to specify which database `psql` should connect to for postgres/postgresql operaitons and facts.

I can into an issue where I wanted to create a postgres role `my_role` with `CREATEDB`, and then connect as that new user to create a database that they owned. Because postgres defaults to connecting to the db with the same name as the role, I would get an error like: `FATAL:  database "my_role" does not exist`.

This method is necessary when using managed postgres services from cloud providers that don't provide superuser access, meaning you can't change the owner of a database.

### CODE REVIEW

**Review by Fizzadar — APPROVED** [review]
Hey @hamishfagg! Thank you for putting this together - this looks great! Sorry it took a while to get to it, I'll get this released shortly :)

**Comment by hamishfagg** [comment]
Hey no problem, thanks for getting to it!

**Comment by hamishfagg** [comment]
Hey @Fizzadar sorry to bother you about this again, do you have an ETA for this to be released?

Thanks

**Comment by Fizzadar** [comment]
@hamishfagg no worries at all, thank you for reminding me! 3.2 will be live in about 5 minutes :)

**Pull request merged**
