### PR TITLE
Update npm.py

### PR DESCRIPTION
**Pull request by gdoumenc**
Seems evident the return was missing.

### CODE REVIEW

**Comment by gdoumenc** [comment]
Your welcome (pyinfra is great..),
Just one question : for files.put is there any reason you made it different if host is @localhost?

**Comment by Fizzadar** [comment]
Thank you :) The files thing - what difference are you seeing? Ideally they should behave the same!

**Comment by gdoumenc** [comment]
Very simple test (or I missed something evident) : 

```
# coding: utf-8

from pyinfra.modules import files

files.put(
    "test1.txt", "test2.txt"
)
```
Doing : 

`pyinfra @local test.py`

Gives :
```
--> Starting operation: Files/Put ('test1.txt', 'test2.txt')
Traceback (most recent call last):
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra/api/operations.py", line 110, in _run_op
    print_output=state.print_output,
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra/api/host.py", line 85, in put_file
    return self.executor.put_file(state, self, *args, **kwargs)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra/api/connectors/local.py", line 112, in put_file
    f.write(file_io.read())
AttributeError: 'str' object has no attribute 'read'
Thu Nov 30 08:24:34 2017 <Greenlet at 0x7fe9541a83d8: _run_op(<pyinfra.api.state.State object at 0x7fe9541d2d30>, @local, '5fa158321e063a93da02a0420600a1664d3f9262')> failed with AttributeError

Traceback (most recent call last):
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/bin/pyinfra", line 11, in <module>
    sys.exit(execute_pyinfra())
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra_cli/__main__.py", line 42, in execute_pyinfra
    cli()
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra_cli/main.py", line 175, in cli
    main(*args, **kwargs)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra_cli/main.py", line 180, in main
    _main(*args, **kwargs)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra_cli/main.py", line 472, in _main
    progress=progress,
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra/api/operations.py", line 335, in run_ops
    if not greenlet.get():
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/gevent/greenlet.py", line 456, in get
    self._raise_exception()
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/gevent/greenlet.py", line 159, in _raise_exception
    reraise(*self.exc_info)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/gevent/_compat.py", line 33, in reraise
    raise value.with_traceback(tb)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra/api/operations.py", line 110, in _run_op
    print_output=state.print_output,
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra/api/host.py", line 85, in put_file
    return self.executor.put_file(state, self, *args, **kwargs)
  File "/home/studiogdo/.local/share/virtualenvs/air-et-sante-6bzRInju/lib/python3.6/site-packages/pyinfra/api/connectors/local.py", line 112, in put_file
    f.write(file_io.read())
AttributeError: 'str' object has no attribute 'read'

```

**Comment by Fizzadar** [comment]
@gdoumenc this should now be fixed as of https://github.com/Fizzadar/pyinfra/pull/126 :)

**Pull request merged**
