### PR TITLE
Add postgresql

### PR DESCRIPTION
**Pull request by hoh**
This branch aims at adding facts and modules to manage PostgreSQL users and databases.
Related to issue #86 

This branch is ready for some early review, but misses some features:

Features:
- [x] Users fact
- [x] User creation
- [x] User creation with superuser privileges
- [ ] User removal
- [ ] User privileges modification
- [x] Database creation
- [ ] Database removal

### CODE REVIEW

**Comment by hoh** [comment]
Thanks, I didn't know these options exist. It might still be an issue for users to have to remember to pass these arguments when they are the default on many distributions.

Should I also remove the `sudo` in the PostgresqlUsers fact ? How should I pass the `sudo_user` then ?

**Comment by hoh** [comment]
@Fizzadar what about the use of `sudo` in the fact ?

**Comment by Fizzadar** [comment]
@hoh sorry for vanishing! Any sudo/sudo_user/su arguments passed to operations will be passed onto facts within those, so you shouldn't need to make any changes for the facts :)

**Comment by Fizzadar** [comment]
@hoh just looked through the changes - all looks good except dropping the sudo stuff from the facts as above :)

**Comment by Fizzadar** [comment]
@hoh I've just pushed the [`mysql` module](https://github.com/Fizzadar/pyinfra/blob/develop/pyinfra/modules/mysql.py) I've been working on; are you cool if I merge this and finish it up for `v0.7`?

**Comment by Fizzadar** [comment]
Merging into a new `postgresql` branch where I'll finish this :)

**Pull request merged**
